### ISSUE TITLE
Conversion error when server is not specified

### ISSUE THREAD

**Issue by julienschuermans** [paperboxai/specio#4]
I just noticed that the conversion from 3.0 to 2.0 fails if I specify my server like this:

```
servers:
- url: /
```

It gives the following error message (on validation of the generated 2.0 spec I assume):
```
Traceback (most recent call last):
  File "/path/to/my/env/bin/specio", line 8, in <module>
    sys.exit(main())
  File "/path/to/my/env/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/my/env/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/path/to/my/env/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/my/env/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/my/env/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/path/to/my/env/lib/python3.8/site-packages/specio/cli.py", line 55, in convert
    specio.convert_from_to_file(spec_file, spec_file_out, from_, to_)
  File "/path/to/my/env/lib/python3.8/site-packages/specio/__init__.py", line 44, in convert_from_to_file
    spec_out = convert_from_file(spec_file, from_type, to_type)
  File "/path/to/my/env/lib/python3.8/site-packages/specio/__init__.py", line 32, in convert_from_file
    spec_out = openapi3_to_espv2_swagger_2.Converter.from_specification(spec)
  File "/path/to/my/env/lib/python3.8/site-packages/specio/converters/openapi3_to_espv2_swagger_2.py", line 33, in from_specification
    return Swagger2Specification(cls.__convert(spec.spec))
  File "/path/to/my/env/lib/python3.8/site-packages/specio/spec.py", line 73, in __init__
    self._validate_spec(raw_spec)
  File "/path/to/my/env/lib/python3.8/site-packages/specio/spec.py", line 91, in _validate_spec
    raise InvalidSpecification.create_from(e)
specio.exceptions.InvalidSpecification: '' does not match '^[^{}/ :\\\\]+(?::\\d+)?$'

Failed validating 'pattern' in schema['properties']['host']:
    {'description': 'The host (name or ip) of the API. Example: '
                    "'swagger.io'",
     'pattern': '^[^{}/ :\\\\]+(?::\\d+)?$',
     'type': 'string'}

On instance['host']:
    ''
```

Everything works as expected when I change it to 
```
servers:
- url: https://api.example.com/v1
```

Maybe this should already be caught during validation of the input spec?

**Comment by nielsbox** [comment]
Hi Julian, Indeed entering `/` should also be possible within Swagger2 spec. I will adjust the validation and align them with the Open API 3.0 validation.

**Comment by nielsbox** [comment]
Was a bit too fast there, should be fixed now. There was an issue with splitting up the servers URL to host and basePath parameters.
